#!/bin/bash
if [ -e "$1" ]; then
	if [ -e "$2" ]; then
		git rm $1
		git commit -m "deleting $2"
		git push origin master
	else
		echo "Nezadal jsi commit!!"
	fi
else
	echo "Nezadal jsi co smazat!!";
fi
